spring.application.name=matrixminute
spring.datasource.url=jdbc:postgresql://localhost:5432/matrixminute
spring.datasource.username=postgres
spring.datasource.password=IL2009SQL@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true